/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tpaao.Main;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.canvas.Canvas;
import javafx.scene.canvas.GraphicsContext;
import javafx.scene.layout.StackPane;
import javafx.scene.paint.Color;
import javafx.stage.Stage;
import tpaao.DataStructure.City;
import tpaao.DataStructure.Network;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        try {

        } catch (IllegalArgumentException e) {
            System.out.println(e.getMessage());
        }
    }
}
